### PR TITLE
Desktop mobile combine

### PR DESCRIPTION
**Pull request by waqaskanju**
-Padding and margin of mobile and desktop changed.

### CODE REVIEW

**Comment by MrRamoun** [comment]
@waqaskanju Can you please, Fix the linter errors

**Comment by waqaskanju** [comment]
yes give me a minute

**Comment by waqaskanju** [comment]
Error fixed kindly review it.

**Review by MrRamoun — CHANGES_REQUESTED** [review]
# 🟡 Just One More Thing 🔸

## Hi @waqaskanju 👋

Great work on making the changes requested by a previous reviewer 👏.

You've done well implementing some of the requested changes 💯, but **there are still some which aren't addressed yet**.

Though, There are some **few** issues 🐛 that you still need to work 🔧 on to go to the next project ⏭️ but you are almost there! 🏃

## Don't Feel frustrated 🤔

I am sure you worked hard 🛠️ to make these changes and actually you have to be proud of them 🥇.

And I understand how much you wanted to get this project approved ✔️ (I was at your place one day 😉). But, don't worry, You still can do it! 💪.

Just apply the changes ♻️ down below 👇 and this time it is going to be approved ✅. Just make sure that you **don't miss any of the changes** requested or introduce any **new bugs** 🐛.

> **Note:** A good tip is to check the box next to every change after you implement it ☑️. And you can also check the full website to see if it is still working after you have implemented the changes.

*Please, reach to [me](#thank-you-for-your-time-🙏-and-call-me-if-you-need-help-or-clarification-☎️) for any help 🪝 or any question ❓. I am always happy to help you 😃.*

## Highlights 🌟

- ✔️ descriptive commit messages
- ✔️ descriptive PR title and description


## Required Changes ♻️

- [ ] [REQUIRED] Please can you center the form button similar to the figma design.
 
Your Website | Figma Design
-------------|---------------
image | image



Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@mrramoun](https://github.com/mrramoun)
- This is My **Twitter**: [@ramoun16](https://twitter.com/ramoun16)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by waqaskanju** [comment]
thanks. button fixed.

**Comment by waqaskanju** [comment]
It would be  better if you just texted me here. I would fix it on the spot and one of my review should not be wasted. Any how thanks for mentioning about button.

**Review by smunozmo — APPROVED** [review]
Hi @waqaskanju, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 




Cheers and Happy coding! 🤓 

## Optional suggestions

- [OPTIONAL] You did a great job! However, the contact form background changes its color from desktop to mobile, it would be better to use the Figma template color.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
